#  ██▒   █▓ ▄▄▄       ██▓     ██▓    ▓█████▓██   ██▓
# ▓██░   █▒▒████▄    ▓██▒    ▓██▒    ▓█   ▀ ▒██  ██▒
#  ▓██  █▒░▒██  ▀█▄  ▒██░    ▒██░    ▒███    ▒██ ██░
#   ▒██ █░░░██▄▄▄▄██ ▒██░    ▒██░    ▒▓█  ▄  ░ ▐██▓░
#    ▒▀█░   ▓█   ▓██▒░██████▒░██████▒░▒████▒ ░ ██▒▓░
#    ░ ▐░   ▒▒   ▓▒█░░ ▒░▓  ░░ ▒░▓  ░░░ ▒░ ░  ██▒▒▒ 
#    ░ ░░    ▒   ▒▒ ░░ ░ ▒  ░░ ░ ▒  ░ ░ ░  ░▓██ ░▒░ 
#      ░░    ░   ▒     ░ ░     ░ ░      ░   ▒ ▒ ░░  
#       ░        ░  ░    ░  ░    ░  ░   ░  ░░ ░     
#      ░                                    ░ ░     
# This file was made and edited with:
# - Emacs
# - Vim
# - Nano
# - GNU Sed
# Created by: https://github.com/Phate6660

## Check if interactive.
if [[ $- != *i* ]] ; then
	return
fi

## Autostart
# Enable completition
source /etc/bash/bashrc.d/bash_completion.sh

# check and change (if needed) window size after every command finishes
shopt -s checkwinsize

## Environmental Variables
# General
export PATH="$PATH:$HOME/.cargo/bin:$HOME/scripts:$HOME/.local/bin"
export PS1="[\@] \u \w \$ " # Prompt example: [12:42 PM] valley ~ $
export LS_COLORS="$(vivid generate molokai)" # Set LS_COLORS to colors generated by https://github.com/sharkdp/vivid
export EDITOR="/usr/bin/vim"
export SUDO_EDITOR="/usr/bin/vim"
export HISTCONTROL="$HISTCONTROL erasedups:ignoreboth" 
export PASTEL_COLOR_MODE=24bit # For https://github.com/sharkdp/pastel

## Functions
# Obtain the weather in your terminal. Change [REDACTED] to either your town, zip code, coordinates, or IP Address.
wttr() {
    local request="wttr.in/${1-[REDACTED]?u}"
    [ "$COLUMNS" -lt 125 ] && request+='?n'
    curl -H "Accept-Language: ${LANG%_*}" --compressed "$request"
}

# How much music. Example output:
# You have:
# ---------
# 116 artists.
# 845 albums.
# 8878 songs.
#
# Which uses up 169GB of storage.
# Also, you have played 17203 complete songs.
#
# Now playing: Prison Song by System Of A Down
# ============================================
# Note: You may need to change some things, like the music directory and the libre.fm user url.
hmm () {
    artists="$(mpc list Artist | sed '/^\s*$/d' | wc -l) artists."
    albums="$(mpc list Album | sed '/^\s*$/d' | wc -l) albums."
    songs="$(mpc list Title | sed '/^\s*$/d' | wc -l) songs."
    size="Which uses up $(\du -hs /mnt/ehdd/Music | cut -c 1-4)B of storage."
    amount="Also, you have played $(w3m -dump https://libre.fm/user/phate6660/stats | grep Total | sed "s/[^0-9]//g") complete songs."
    status="$(w3m -dump https://libre.fm/user/phate6660/ | grep "playing" | sed 's/×\ //g')"
    echo -e "\nYou have:\n---------\n$artists\n$albums\n$songs\n\n$size\n$amount\n\n$status\n"
}

# Update without syncing. Useful for when something goes wrong and you need to update again, but don't wanna sync again.
update() {
    sudo emerge -avuDN --with-bdeps y @world
    sudo emerge -Dac
    sudo revdep-rebuild -i
    read -p "Your system has been updated. Press [ENTER] to continue."
}

updatefull() {
    sudo emerge --sync                      # Sync repositories
    sudo emerge -avuDN --with-bdeps @world  # Update packages
    sudo emerge -Dac                        # Remove un-needed packages
    sudo revdep-rebuild -i                  # Rebuild any required dependencies
    read -p "Your system has been updated. Press [ENTER] to continue."
}

# Play a song via youtube search. Example: play world coming down type o negative
play() {
    search=$@
    search=${search// /+}
    mpv ytdl://ytsearch:"$search" --ytdl-format bestaudio
}

# Neatly output contents of $PATH.
lspath() { echo -e "$(echo "$PATH" | sed 's/\:/\\n/g')"; }

# Function to list all files in $PWD.
list(){ for file in *; do printf '%s\n' "$file"; done; }

# With arguments, play video with mpv. Without arguments, open invido.us in firefox.
yt() { if [ -z ${1+x} ]; then firefox --new-tab invidio.us; else mpv "$1"; fi; }

# Use python as a calculator. Example: calc 2*3+4/5-6
calc() { python -c "print($@)"; }

pvre() {
    sudo protonvpn d
    sudo protonvpn c -f
    sudo protonvpn s
    read -p 'Press [ENTER] to continue.'
    speedtest-cli --secure --no-upload
}

pvp2p() {
    sudo protonvpn d
    sudo protonvpn c --p2p
    sudo protonvpn s
}

# Compare 2 directories for differences. There will be no output if both directories are identical. Includes subdirectories too.
# Example: atts $HOME/example $HOME/example2
atts() { diff -r -q "$@"; }

## Aliases
alias rsfetch="rsfetch --no-wm-de -hup portage -L /mnt/ehdd/Pictures/ascii/leaf" # Shameless self-advertizing: https://github.com/rsfetch/rsfetch
alias myip="curl --silent https://ipecho.net/plain; echo" # Display public IP Address.
alias ss="ss -ntlp"
alias aria="aria2c -c -j16 -x16 -s16 -k 1M"

alias grep="rg -i --color=auto"
alias ls="ls -Fa --color=auto"
alias cat="cat -n"
alias mkdir='mkdir -pv'
alias mv="mv -iv"
alias cp="cp -iv"
alias rm="rm -iv"
alias ps="ps auxf"
alias pse="\ps -e --forest"
alias psg="\ps aux | grep -v grep | grep -i -e VSZ -e"
alias psr="\ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head"
alias pst="\ps -eo pid,comm,lstart,etimes,time,args"

alias mus='ncmpcpp -c ~/.ncmpcpp/config-rwb'
alias lyrics='ncmpcpp -c ~/.ncmpcpp/config-lyrics'
alias scriblog='clear; tail -f ~/.mpdscribble/mpdscribble.log'

alias ytdl='youtube-dl'

alias pvpn="sudo protonvpn"
alias pvstat="sudo pvpn --status" # Check ProtonVPN's status.
alias speed="speedtest-cli --secure --no-upload" # Speed test. Uses only https and only tests download speed.

alias merge="sudo emerge -atv" # Install package(s). a = ask, t = tree, v = verbose.
alias changed="sudo emerge --ask --changed-use --deep @world" # Use after changing USE flags.
alias emake="sudo -e /etc/portage/make.conf" # Edit make.conf with $SUDO_EDITOR.
alias searchfor="emerge -s" # Search for a package.
alias rem="sudo emerge -avc" # Remove package(s). c = depclean.
alias frem="sudo emerge -avC" # Force remove package(s). C = unmerge.
alias clean="sudo emerge -Dac; sudo revdep-rebuild -i" # Remove any un-needed packages, rebuild anything necessary. D = deep.
alias portup="sudo emerge -a1 sys-apps/portage" # One-shot merge portage, only used when portage needs to update (usually).
alias genlop="sudo genlop -it" # Display info for emerged ebuild(s). i = info, t = calculate merge time.
alias lsuse="portageq envvar USE | xargs -n 1" # Neatly output the set USE flags for portage.
alias lsfeat="portageq envvar FEATURES | xargs -n 1" # Neatly output the set features for portage.
alias lspkg="printf '%s\n' /var/db/pkg/*/*/" # List installed packages.
alias pkgsum="sudo qlop -c | grep total" # Total time, along with total merges, unmerges, and syncs for portage.
