#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

### keybindings ###
Mod=Mod4                                                    # Use the super key as the main modifier

hc keybind Ctrl-Mod1-Delete  quit                            # Quit herbstluftwm
hc keybind Mod1-Shift-r      reload                          # Reload the configuration
hc keybind Mod1-Shift-c      close                           # Close currently focused window
hc keybind Mod1-Return       spawn /home/valley/scripts/term-trans # Spawn uxterm (transparent)
hc keybind Mod1-Shift-Return spawn uxterm                    # Spawn uxterm
hc keybind $Mod-t            spawn /home/valley/scripts/general tag # Display currently focused tag through notification
hc keybind $Mod-w            spawn sudo -u ff firefox        # Spawn Firefox
hc keybind XF86AudioPlay     spawn mpc toggle                # Play/Pause song (MPD)
hc keybind XF86AudioNext     spawn mpc next                  # Play next song (MPD)
hc keybind XF86AudioPrev     spawn mpc prev                  # Play previous song (MPD)
hc keybind $Mod-Mod1-g       spawn rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' # Spawn clipbord menu in Rofi
hc keybind $Mod-f            spawn pcmanfm                   # Spawn file manager
hc keybind $Mod-Shift-f      spawn filezilla                 # Spawn filezilla
hc keybind Ctrl-Mod1-space   spawn rofi -show run            # Spawn Rofi (-run)
hc keybind $Mod-m            spawn /home/valley/scripts/general mus # Spawn notification with music info
hc keybind $Mod-n            spawn /home/valley/scripts/general date # Spawn notification with current time and date (in 12 hr format)
hc keybind $Mod-d            spawn mpv dvd://                # Play DVD using mpv and dvdnav (slow but most compatible)
hc keybind $Mod-Shift-d      spawn mpv dvdread://            # Play DVD using mpv and dvdread (fast yet least compatible)
hc keybind Print             spawn scrot -uz -e 'mv $f ~/pictures/scrot/' # Take a screenshot, then move the screenshot to ~/pictures/scrot
hc keybind $Mod-Shift-b      spawn /home/valley/downloads/blender-2.80-163996b68129-linux-glibc217-x86_64/blender # Spawn Blender 2.80
hc keybind $Mod-b            spawn /home/valley/bin/bwmenu   # Spawn Bitwarden Rofi menu
hc keybind $Mod-Shift-u      spawn udiskie -a -N             # Spawn udiskie (only needed for if udiskie fails to autostart for some reason)
hc keybind $Mod-x            spawn slock                     # Lock the screen
hc keybind $Mod-a            spawn /home/valley/scripts/script-dmenu # Rofi (-dmenu) for launching and editing scripts.
hc keybind Ctrl-q            spawn sh -c "echo 'You almost quit your program' | rofi -dmenu -p 'You fucked up'" # Give warning for almost quitting application
hc keybind $Mod-i            spawn /home/valley/scripts/general ip # Show IP Address in notification
hc keybind $Mod-k            spawn /home/valley/scripts/keybinds # Display keybindings

### basic movement ###
# focusing clients
hc keybind Mod1-Left  focus left
hc keybind Mod1-Down  focus down
hc keybind Mod1-Up    focus up
hc keybind Mod1-Right focus right

# moving clients
hc keybind Mod1-Shift-Left  shift left
hc keybind Mod1-Shift-Down  shift down
hc keybind Mod1-Shift-Up    shift up
hc keybind Mod1-Shift-Right shift right

### tags ###
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Mod1-$key" use_index "$i"
        hc keybind "Mod1-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind Ctrl-Mod1-Right use_index +1 --skip-visible
hc keybind Ctrl-Mod1-Left  use_index -1 --skip-visible

# layouting
hc keybind Ctrl-Mod1-r remove
hc keybind Ctrl-Mod1-s floating toggle
hc keybind Ctrl-Mod1-f fullscreen toggle
hc keybind Ctrl-Mod1-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

### mouse ###
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

### theme ###
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

### misc settings ###
hc set gapless_grid 1
hc set_layout grid
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set focus_follows_mouse 1

### rules ###
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class="Firefox" floating=on
hc rule class="Navigator" floating=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc set_monitors 1366x768 1438x900+1366+0

### autostart once  ###
if hc silent new_attr bool my_not_first_autostart ; then
    udiskie -a -N &
    uxterm -e /home/valley/scripts/auto &
fi
