#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

### keybindings ###
Mod=Mod4   # Use the super key as the main modifier

hc keybind Ctrl-Mod1-Delete quit
hc keybind Mod1-Shift-r reload
hc keybind Ctrl-Shift-c close
hc keybind $Mod-t spawn uxterm
hc keybind $Mod-Shift-t spawn term-dmenu
hc keybind $Mod-g spawn gimp
hc keybind $Mod-w spawn qutebrowser
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86AudioNext spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev
hc keybind $Mod-Mod1-g spawn rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
hc keybind $Mod-f spawn uxterm -e "FFF_FAV1=/run/media/valley FFF_FAV2=/home/ff FFF_FAV3=~/downloads FFF_FAV4=~/downloads/github FFF_FAV5=~/projects fff"
hc keybind Ctrl-Mod1-space spawn rofi -show run
hc keybind $Mod-n spawn musinfo
hc keybind $Mod-d spawn mpv dvd://
hc keybind $Mod-Shift-d spawn mpv dvdread://
hc keybind Print spawn scrot -bz -e 'mv $f ~/pictures/scrot/'
hc keybind $Mod-b spawn blender
hc keybind $Mod-Shift-b spawn bwmenu
hc keybind $Mod-Shift-u spawn udiskie -a -N
hc keybind $Mod-x spawn xscreensaver-command -lock
hc keybind $Mod-r spawn RocketLauncher2
hc keybind $Mod-a spawn script-dmenu
hc keybind $Mod-v spawn vncviewer -passwordfile=.vncpasswd 192.168.1.152:5901
hc keybind Mod1-Tab spawn xwinmosaic -C

# basic movement
# focusing clients
hc keybind Mod1-Left  focus left
hc keybind Mod1-Down  focus down
hc keybind Mod1-Up    focus up
hc keybind Mod1-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind Mod1-Shift-Left  shift left
hc keybind Mod1-Shift-Down  shift down
hc keybind Mod1-Shift-Up    shift up
hc keybind Mod1-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Mod1-$key" use_index "$i"
        hc keybind "Mod1-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind Ctrl-Mod1-Right use_index +1 --skip-visible
hc keybind Ctrl-Mod1-Left  use_index -1 --skip-visible

# layouting
hc keybind Ctrl-Mod1-r remove
hc keybind Ctrl-Mod1-s floating toggle
hc keybind Ctrl-Mod1-f fullscreen toggle
hc keybind Ctrl-Mod1-p pseudotile toggle
herbstclient set default_frame_layout 3
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind Mod1-Button1 move
hc mousebind Mod1-Button2 zoom
hc mousebind Mod1-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Xx]winmosaic' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

if hc silent new_attr bool my_not_first_autostart ; then
    udiskie -a -N &
    uxterm -e /home/valley/scripts/auto &
fi
