#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

### keybindings ###
# User super/hyper as the main modifier
Mod=Mod4

# Quit herbstluftwm
hc keybind Ctrl-Mod1-Delete  quit
# Reload the configuration
hc keybind Mod1-Shift-r      reload
# Close the currently focused window
hc keybind Mod1-Shift-c      close
# Spawn alacritty
hc keybind Mod1-Return spawn alacritty
# Spawn a transparent xterm
hc keybind Mod1-Shift-Return       spawn /home/valley/scripts/general term
# Toggle/next/previious audio (mpris -- spotify or MPD)
hc keybind XF86AudioPlay     spawn playerctl -p spotify,strawberry play-pause
hc keybind XF86AudioNext     spawn playerctl -p spotify,strawberry next
hc keybind XF86AudioPrev     spawn playerctl -p spotify,strawberry previous
# Launcher
hc keybind Ctrl-Mod1-space   spawn rofi -show run
# Music info (Spotify or Strawberry) in notification
hc keybind $Mod-m      spawn /home/valley/scripts/general musinf2
# Time and date in notification
hc keybind $Mod-n            spawn /home/valley/scripts/general date
# Take a screenshot
hc keybind Print             spawn /home/valley/scripts/general scr
# Password manager
hc keybind $Mod-b            spawn bwmenu
# Lock the screen
hc keybind $Mod-x            spawn slock
# Accidental-window-closing-shield
hc keybind Ctrl-q            spawn dunstify "Oops:" "You almost quit your program!"
# View system info in notification
hc keybind $Mod-o            spawn /home/valley/scripts/general fetch

### basic movement ###
# focusing clients
hc keybind Mod1-Left  focus left
hc keybind Mod1-Down  focus down
hc keybind Mod1-Up    focus up
hc keybind Mod1-Right focus right

# moving clients
hc keybind Mod1-Shift-Left  shift left
hc keybind Mod1-Shift-Down  shift down
hc keybind Mod1-Shift-Up    shift up
hc keybind Mod1-Shift-Right shift right

### tags ###
tag_names=( {1..10} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "Mod1-$key" use_index "$i"
        hc keybind "Mod1-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind Ctrl-Mod1-Right use_index +1 --skip-visible
hc keybind Ctrl-Mod1-Left  use_index -1 --skip-visible

# layouting
hc keybind Ctrl-Mod1-r remove
hc keybind Ctrl-Mod1-s floating toggle
hc keybind Ctrl-Mod1-f fullscreen toggle
hc keybind Ctrl-Mod1-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space  cycle_layout +1 grid

### mouse ###
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

### theme ###
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 15
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

### misc settings ###
hc set gapless_grid 1
hc set_layout grid
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set focus_follows_mouse 1

### rules ###
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
hc set_monitors 1280x1024 1440x900+1280+124
