# Shell variables
# Generated by 'wal'
wallpaper='/mnt/ehdd/Pictures/wallpapers/8md6RX.png'

# Special
background='#060605'
foreground='#dedede'
cursor='#dedede'

# Colors
color0='#060605'
color1='#A72C13'
color2='#7D825F'
color3='#919563'
color4='#9DA08F'
color5='#C3BD90'
color6='#CFC896'
color7='#dedede'
color8='#9b9b9b'
color9='#A72C13'
color10='#7D825F'
color11='#919563'
color12='#9DA08F'
color13='#C3BD90'
color14='#CFC896'
color15='#dedede'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
