--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/mnt/ehdd/Pictures/wallpapers/8md6RX.png"

-- Special
background="#060605"
foreground="#dedede"
cursor="#dedede"

-- Colors
color0="#060605"
color1="#A72C13"
color2="#7D825F"
color3="#919563"
color4="#9DA08F"
color5="#C3BD90"
color6="#CFC896"
color7="#dedede"
color8="#9b9b9b"
color9="#A72C13"
color10="#7D825F"
color11="#919563"
color12="#9DA08F"
color13="#C3BD90"
color14="#CFC896"
color15="#dedede"
