#! /bin/sh

sxhkd &

bspc monitor HDMI-0 -d I II III IV V
bspc monitor VGA-0 -d VI VII VIII IX X

bspc config border_width         5
bspc config window_gap           7

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc rule -a Emacs state=tiled
bspc rule -a FreeTube state=floating
bspc rule -a Ripcord state=floating
bspc rule -a Gimp state=floating
bspc rule -a bite state=floating
