#!/bin/bash

###
### Edit configuration files in the system, select them using 'rofi -dmenu'. 
###

## Lists of options to appear in rofi.
declare -a main=("Gentoo/\nBASH/.bashrc\nEmacs/init.el\nherbstluftwm/\nQutebrowser/config.py\nNano/.nanorc")
declare -a gentoo=("make.conf\nkernel")
declare -a herb=("autostart\npanel.sh")

## Display the rofi menu, save user selection to variable 'choice'.
choice=$(echo -e "${main[@]}" | rofi -dmenu -p "confmenu")

## What to do depending on the user's selection.
if [ "$choice" = "Gentoo/" ]; then
    choice2=$(echo -e "${gentoo[@]}" | rofi -dmenu -p "confmenu/Gentoo")
    if [ "$choice2" = "make.conf" ]; then
	uxterm -e makemod
    elif [ "$choice2" = "kernel" ]; then
	uxterm -e kernmod
    fi
elif [ "$choice" = "BASH/.bashrc" ]; then
    uxterm -e emacs -nw ~/.bashrc
elif [ "$choice" = "Emacs/init.el" ]; then
    uxterm -e emacs -nw ~/.emacs.d/init.el
elif [ "$choice" = "herbstluftwm/" ]; then
    choice3=$(echo -e "${herb[@]}" | rofi -dmenu -p "confmenu/herbstluftwm")
    if [ "$choice3" = "autostart" ]; then
	uxterm -e emacs -nw ~/.config/herbstluftwm/autostart
    elif [ "$choice3" = "panel.sh" ]; then
	uxterm -e emacs -nw ~/.config/herbstluftwm/panel.sh
    fi
elif [ "$choice" = "Qutebrowser/config.py" ]; then
    uxterm -e emacs -nw ~/.config/qutebrowser/config.py
elif [ "$choice" = "Nano/.nanorc" ]; then
    uxterm -e emacs -nw ~/.nanorc
fi
