#!/bin/bash

###
### Various Gentoo-specific operations available through rofi (with -dmenu).
###

## Lists of options
declare -a main=("Update Packages\nInstall Packages\nRe-Emerge Packages\nRemove Packages\nView Package List")
declare -a up=("Update System\nUpdate Portage\nUpdate Specific Packages")

## Choice making
choice=$(echo -e "${main[@]}" | rofi -dmenu -p "genmenu")

## What to do
if [ "$choice" = "Update Packages" ]; then
    choice2=$(echo -e "${up[@]}" | rofi -dmenu -p "genmenu/update")
    if [ "$choice2" = "Update System" ]; then
	pass=$(rofi -dmenu -p "Please enter your password")
        syn=$(echo "$pass" | sudo -S emerge --sync)
	echo "$syn" | rofi -dmenu -p "Finished syncing, press [ESC] or [ENTER] to start updating"
        upd=$(echo "$pass" | sudo -S emerge -vuDN world)
	echo "$upd" | rofi -dmenu -p "Finished updating, press [ESC] or [ENTER] start depcleaning"
        dep=$(echo "$pass" | sudo -S emerge -Dv --depclean)
	echo "$dep" | rofi -dmenu -p "Finished depcleaning, press [ESC] or [ENTER] to revdep-rebuild"
        rev=$(echo "$pass" | sudo -S revdep-rebuild -i)
	echo "$rev" | rofi -dmenu -p "Finished revdep-rebuild, press [ESC] or [ENTER] to exit"
        unset pass
	exit 0
    elif [ "$choice2" = "Update Portage" ]; then
	pass=$(rofi -dmenu -p "Please enter your password")
        port=$(echo "$pass" | sudo -S emerge --oneshot sys-apps/portage)
	echo "$port" | rofi -dmenu -p "Finished updating portage, press [ESC] or [ENTER] to exit"
        unset pass
	exit 0
    elif [ "$choice2" = "Update Specific Packages" ]; then
	pass=$(rofi -dmenu -p "Please enter your password")
	pkgs=$(rofi -dmenu -p "Enter the packages you wish to update")
	pkup=$(echo "$pass" | sudo -S emerge -v "$pkgs")
	echo "$pkup" | rofi -dmenu -p "Finished updating packages, press [ESC] or [ENTER] to exit"
	unset pass
	exit 0
    fi
elif [ "$choice" = "Install Packages" ]; then
    pass=$(rofi -dmenu -p "Please enter your password")
    pkgs=$(rofi -dmenu -p "Enter the packages you wish to install")
    pkin=$(echo "$pass" | sudo -S emerge -v "$pkgs")
    echo "$pkin" | rofi -dmenu -p "Finished installing packages, press [ESC] or [ENTER] to exit"
    unset pass
    exit 0
elif [ "$choice" = "Re-Emerge Packages" ]; then
    pass=$(rofi -dmenu -p "Please enter your password")
    reem=$(echo "$pass" | sudo -S emerge --changed-use --deep @world)
    echo "$reem" | rofi -dmenu -p "Finished re-emerging packages, press [ESC] or [ENTER] to exit"
    unset pass
    exit 0
elif [ "$choice" = "Remove Packages" ]; then
    pass=$(rofi -dmenu -p "Please enter your password")
    pkgs=$(rofi -dmenu -p "Enter the packages you wish to remove")
    pkno=$(echo "$pass" | sudo -S emerge -Dv --depclean "$pkgs")
    echo "$pkno" | rofi -dmenu -p "Finished removing packages, press [ESC] or [ENTER] to exit"
    unset pass
    exit 0
elif [ "$choice" = "View Package List" ]; then
    pkgs=$(qlist -I)
    echo "$pkgs" | rofi -dmenu -p "Press [ESC] or [ENTER] to exit"
    unset pass
    exit 0
fi
