#!/bin/bash

###
### Modify the kernel using 'make menuconfig', optionally recompile kernel afterwards.
###

# Obtain root shell.
sudo -i

# Enter kernel source directory.
cd /usr/src/linux

# Configure kernel with menuconfig.
make menuconfig

# Ask if user would like to compile and install the kernel.
echo "Would you like to compile and install the kernel?"
read a

# What to do depending on the user's answer.
if [ "$a" = "yes" ]; then
    # Ask if user would like to re-emerge and prepare any external kernel modules.
    echo -e "Would you like to re-emerge and prepare external kernel modules? (yes/no)\nThis is typically only needed when upgrading to a new kernel version."
    read b
    if [ "$b" = "yes" ]; then
	emerge --ask @module-rebuild
	make modules_prepare
    else
	break
    fi
    # Clear the screen.
    clear
    # Obtain amount of cores.
    c="$(lscpu -p | grep -v '#' | sort -u -t , -k 2,4 | wc -l)"
    # Add 1 to the amount of cores.
    c="$(echo "$c+1" | bc --)"
    # Begin compiling.
    make -j$c
    make modules_install
    # Install kernel.
    make install
    # Generate new initramfs.
    genkernel --install initramfs
    # Generate GRUB config.
    grub-mkconfig -o /boot/grub/grub.cfg
else
    read -p "You chose not to recompile and install. Don't forget to later. Press [ENTER] to exit."
    exit 0
fi
