#!/bin/bash

dur="$(playerctl metadata --format '{{ duration(position) }}/{{ duration(mpris:length) }}')"
sta="$(playerctl status --format "{{ uc(status) }}")"
art="$(mpc -f %artist% | head -n1)"
alb="$(mpc -f %album% | head -n1)"
tit="$(mpc -f %title% | head -n1)"
dat="$(mpc -f %date% | head -n1)"
gen="$(mpc -f %genre% | head -n1)"
fil="$(playerctl metadata xesam:url)"
cod="${fil##*.}"

echo -e "[$sta] $tit [$dur]\n[$dat] $alb\n$art\n$gen\n$cod" | dzen2 -l 4 -p 7 -fg "#FFFFFF" -bg "#0000d0" -h 16 -sa c -xs 2
