#!/bin/bash

###
### Launch or edit scripts from 'rofi'. Edit in 'emacs'.
###

## List of options to appear in rofi.
declare -a main=("Execute\nEdit")
declare -a list=("Anime Dmenu\nConfiguration Dmenu\nGentoo Dmenu\nmpc-rofi\nMusic Info\nYouTube 2 Invidio")
declare -a general=("date")

## What to do.
choice2=$(echo -e "${main[@]}" | rofi -dmenu -p "scriptmenu - Would you like to execute or edit?")
if [ "$choice2" = "Execute" ]; then
    choice3=$(echo -e "${list[@]}" | rofi -dmenu -p "scriptmenu - What would you like to execute?")
    if [ "$choice3" = "Anime Dmenu" ]; then
	animenu-dmenu
    elif [ "$choice3" = "Configuration Dmenu" ]; then
	confmenu-dmenu
    elif [ "$choice3" = "Gentoo Dmenu" ]; then
	genmenu-dmenu
    elif [ "$choice3" = "mpc-rofi" ]; then
	mus-dmenu
    elif [ "$choice3" = "Music Info" ]; then
	musinfo
    elif [ "$choice3" = "YouTube 2 Invidio" ]; then
	k3rmit -e yt2iv
    fi
elif [ "$choice2" = "Edit" ]; then
    choice3=$(echo -e "${list[@]}" | rofi -dmenu -p "scriptmenu - What would you like to edit?")
    if [ "$choice3" = "animenu-dmenu" ]; then
	uxterm -e emacs -nw ~/scripts/animenu-dmenu
   elif [ "$choice3" = "colortest" ]; then
	uxterm -e emacs -nw ~/scripts/colortest
    elif [ "$choice3" = "confmenu-dmenu" ]; then
	uxterm -e emacs -nw ~/scripts/confmenu-dmenu
    elif [ "$choice3" = "genmenu-dmenu" ]; then
	uxterm -e emacs -nw ~/scripts/genmenu-dmenu
    elif [ "$choice3" = "mpc-rofi" ]; then
        uxterm -e emacs -nw ~/scripts/mus-dmenu
    elif [ "$choice3" = "musinfo" ]; then
	uxterm -e emacs -nw ~/scripts/musinfo
    elif [ "$choice3" = "yt2iv" ]; then
	uxterm -e emacs -nw ~/scripts/yt2iv
    fi
fi
