#!/bin/bash

c0="$(sensors -f | \grep ^Core | sed -n 1p | awk -F\  '{ print $3 }' | sed s/+//g)"
c0h="$(sensors -f | \grep ^Core | sed -n 1p | awk -F\  '{ print $6 }' | sed -e s/,//g -e s/+//g)"
c1="$(sensors -f | \grep ^Core | sed -n 2p | awk -F\  '{ print $3 }' | sed s/+//g)"
c1h="$(sensors -f | \grep ^Core | sed -n 2p | awk -F\  '{ print $6 }' | sed -e s/,//g -e s/+//g)"
c2="$(sensors -f | \grep ^Core | sed -n 3p | awk -F\  '{ print $3 }' | sed s/+//g)"
c2h="$(sensors -f | \grep ^Core | sed -n 3p | awk -F\  '{ print $6 }' | sed -e s/,//g -e s/+//g)"
c3="$(sensors -f | \grep ^Core | sed -n 4p | awk -F\  '{ print $3 }' | sed s/+//g)"
c3h="$(sensors -f | \grep ^Core | sed -n 4p | awk -F\  '{ print $6 }' | sed -e s/,//g -e s/+//g)"

echo -e "0: $c0/$c0h\n1: $c1/$c1h\n2: $c2/$c2h\n3: $c3/$c3h"
